dist: focal
language: cpp
git:
  depth: 1

install:
  - if [[ -n "$CUSTOM_COMPILER" ]]; then eval "${CUSTOM_COMPILER}"; fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest -V

matrix:
  include:
    #################################################################################
    # Linux / GCC
    # GCC 4.8 and older doesn't support C++14
    #################################################################################
    # gcc 10
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
      env: CUSTOM_COMPILER="CC=gcc-10 && CXX=g++-10"

    #################################################################################
    # Linux / clang
    #################################################################################
    # clang 11
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-focal-11
          packages:
            - clang-11
            - g++-10
      env: CUSTOM_COMPILER="CC=clang-11 && CXX=clang++-11"
    # clang 10
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-focal-10
          packages:
            - clang-10
            - g++-10
      env: CUSTOM_COMPILER="CC=clang-10 && CXX=clang++-10"

    #################################################################################
    # macosx
    #################################################################################
    # osx (xcode 12.2)
    - os: osx
      osx_image: xcode12.2

    #################################################################################
    # Windows
    #################################################################################
    # Windows (Windows server 1803)
    # Not working for now
    # - os: windows
