dist: focal
language: cpp
git:
  depth: 1

install:
  - if [[ -n "$CUSTOM_COMPILER" ]]; then eval "${CUSTOM_COMPILER}"; fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest -V

matrix:
  include:
    #################################################################################
    # Linux / GCC
    # GCC 4.8 and older doesn't support C++14
    #################################################################################
    # gcc 10
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
      env: CUSTOM_COMPILER="CC=gcc-10 && CXX=g++-10"
    # gcc 9
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env: CUSTOM_COMPILER="CC=gcc-9 && CXX=g++-9"
    # gcc 8
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: CUSTOM_COMPILER="CC=gcc-8 && CXX=g++-8"
    # gcc 7
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: CUSTOM_COMPILER="CC=gcc-7 && CXX=g++-7"
    # gcc 6
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: CUSTOM_COMPILER="CC=gcc-6 && CXX=g++-6"
    # gcc 5
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: CUSTOM_COMPILER="CC=gcc-5 && CXX=g++-5"
    # gcc 4.9
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: CUSTOM_COMPILER="CC=gcc-4.9 && CXX=g++-4.9"

    #################################################################################
    # Linux / clang
    #################################################################################
    # clang 11
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-focal-11
          packages:
            - clang-11
            - g++-10
      env: CUSTOM_COMPILER="CC=clang-11 && CXX=clang++-11"
    # clang 10
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-focal-10
          packages:
            - clang-10
            - g++-10
      env: CUSTOM_COMPILER="CC=clang-10 && CXX=clang++-10"
    # clang 9
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-focal-9
          packages:
            - clang-9
            - g++-10
      env: CUSTOM_COMPILER="CC=clang-9 && CXX=clang++-9"
    # clang 8
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-focal-8
          packages:
            - clang-8
            - g++-9
      env: CUSTOM_COMPILER="CC=clang-8 && CXX=clang++-8"
    # clang 7
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-focal-7
          packages:
            - clang-7
            - g++-9
      env: CUSTOM_COMPILER="CC=clang-7 && CXX=clang++-7"
    # clang 6.0
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-focal-6.0
          packages:
            - clang-6.0
            - g++-9
      env: CUSTOM_COMPILER="CC=clang-6.0 && CXX=clang++-6.0"
    # clang 5.0
    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-5.0
          packages:
            - clang-5.0
            - g++-9
      env: CUSTOM_COMPILER="CC=clang-5.0 && CXX=clang++-5.0"
    # clang 4.0
    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-4.0
          packages:
            - clang-4.0
            - g++-9
      env: CUSTOM_COMPILER="CC=clang-4.0 && CXX=clang++-4.0"
    # clang 3.9
    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-3.9
          packages:
            - clang-3.9
            - g++-9
      env: CUSTOM_COMPILER="CC=clang-3.9 && CXX=clang++-3.9"
    # clang 3.8
    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-3.8
          packages:
            - clang-3.8
            - g++-9
      env: CUSTOM_COMPILER="CC=clang-3.8 && CXX=clang++-3.8"

    #################################################################################
    # macosx
    #################################################################################
    # osx (xcode 12.2)
    - os: osx
      osx_image: xcode12.2
      before_install:
        - brew install re2c
    # osx (xcode 11)
    - os: osx
      osx_image: xcode11.6
      before_install:
        - brew install re2c
    # osx (xcode 10.3)
    - os: osx
      osx_image: xcode10.3
      before_install:
        - brew install re2c
    # osx (xcode 9.4)
    - os: osx
      osx_image: xcode9.4
      before_install:
        - brew install re2c
    # osx (xcode 8.3)
    - os: osx
      osx_image: xcode8.3
      before_install:
        - brew update
        - brew install --build-from-source re2c

    #################################################################################
    # Windows
    #################################################################################
    # Windows (Windows server 1803)
    # Not working for now
    # - os: windows
